### ISSUE TITLE
Unknown error when attempting to install

### ISSUE THREAD

**Issue by Tzrlk** [chef/libyajl2-gem#10]
```shell
c:\tools\ruby23\lib\ruby\gems\2.3.0\extensions\x64-mingw32\2.3.0\libyajl2-1.2.0>cat gem_make.out
current directory: C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/libyajl2-1.2.0/ext/libyajl2
C:/tools/ruby23/bin/ruby.exe -r ./siteconf20161214-11544-11jgtg7.rb extconf.rb
creating Makefile
/c/tools/ruby23/lib/ruby/gems/2.3.0/gems/libyajl2-1.2.0/ext/libyajl2
extconf.rb:104:in `makemakefiles': unhandled exception
        from extconf.rb:138:in `<main>'

extconf failed, exit code 1

c:\tools\ruby23\lib\ruby\gems\2.3.0\extensions\x64-mingw32\2.3.0\libyajl2-1.2.0>ls
gem_make.out

c:\tools\ruby23\lib\ruby\gems\2.3.0\gems\libyajl2-1.2.0\ext\libyajl2>cat make.out
make: *** No rule to make target `/C/tools/ruby23/include/ruby-2.3.0/ruby.h', needed by `yajl.o'.  Stop.
```

I'm on Windows 10.

**Comment by tas50** [comment]
I believe you're missing http://rubyinstaller.org/add-ons/devkit/

**Comment by lamont-granquist** [comment]
> make: *** No rule to make target `/C/tools/ruby23/include/ruby-2.3.0/ruby.h', needed by `yajl.o'.  Stop.

cygwin?  if so, that isn't really supported beyond "PR accepted".  if you can solve the problem, we'll merge the PR, otherwise its wontfix, and we don't recommend trying to fight with it.

**Comment by Tzrlk** [comment]
@tas50, yep, that was exactly it. #fml This happens every time I set up a new dev environment.
