### ISSUE TITLE
Uninformative error message during build when `make` is not installed

### ISSUE THREAD

**Issue by sparr** [chef/libyajl2-gem#25]
# Describe the problem
When trying to install this gem without `make` installed, an unhelpful error message is produced that requires looking at the gem source to figure out.

## Software Version
1.2.0
Ubuntu 20.04

## Replication Case
`gem install libyajl2`

## Stacktrace

<details><summary>  </summary>
error message during a slightly more involved attempt to install than the simple case above

```
Installing libyajl2 1.2.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ubuntu/src/better-chef-rundeck/vendor/bundle/ruby/2.5.0/gems/libyajl2-1.2.0/ext/libyajl2
/usr/bin/ruby2.5 -r ./siteconf20201009-12357-1c5mlj.rb extconf.rb
creating Makefile
/home/ubuntu/src/better-chef-rundeck/vendor/bundle/ruby/2.5.0/gems/libyajl2-1.2.0/ext/libyajl2
extconf.rb:104:in `makemakefiles': unhandled exception
	from extconf.rb:138:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/ubuntu/src/better-chef-rundeck/vendor/bundle/ruby/2.5.0/gems/libyajl2-1.2.0 for inspection.
Results logged to /home/ubuntu/src/better-chef-rundeck/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/libyajl2-1.2.0/gem_make.out

An error occurred while installing libyajl2 (1.2.0), and Bundler cannot continue.
Make sure that `gem install libyajl2 -v '1.2.0'` succeeds before bundling.

In Gemfile:
  chef was resolved to 13.6.4, which depends on
    chef-zero was resolved to 13.1.0, which depends on
      ffi-yajl was resolved to 2.3.1, which depends on
        libyajl2
```
</details>

**Comment by adsk-stoddai** [comment]
If an embedded chef gem requires FFI, you will have to ensure your environment already has make/gcc tools installed (like `build-essential` on Ubuntu).

OS packages normally install during Chef's 2nd stage (`converge`), so make/gcc might not be available during Chef's 1st stage (`compile`), which might happen if something like Test Kitchen tries to install `libyajl2` during a compile phase (or before build packages are available).

If you have gems that need to be added to Chef's embedded library, and participate in the compile phase, you likely have three options:
- install FFI build dependencies before running chef (this may require creating intermediate vagrant/ec2/container images)
- re-package chef client utilities to include any pre-compiled gems requiring FFI
- build a container to run chef, including the FFI-built gems
