### ISSUE TITLE
Hang on parsing documentation

### ISSUE THREAD

**Issue by michaelachrisco** [chef/libyajl2-gem#5]
I am using the madscience gem, which requires this gem.

The generation of documentation is using 100% of the CPU and taking a long time while seemingly not doing anything. 

`Parsing documentation for libyajl2-1.2.0`
Ill give an update if I find anything.

**Comment by michaelachrisco** [comment]
I also see something similar at: https://bugzilla.redhat.com/show_bug.cgi?id=1180367

**Comment by michaelachrisco** [comment]
```Bash
$ gem clean 
Cleaning up installed gems...
Clean Up Complete

$ gem install madscience
Successfully installed madscience-0.0.20
Parsing documentation for madscience-0.0.20
Done installing documentation for madscience after 0 seconds
1 gem installed

$ fatal: Not a git repository (or any of the parent directories): .git
/Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find blanket_wrapper-1.1.0 in any of the sources (Bundler::GemNotFound)
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/definition.rb:132:in `specs'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/definition.rb:177:in `specs_for'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/definition.rb:166:in `requested_specs'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:13:in `setup'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler.rb:122:in `setup'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/gems/madscience-0.0.20/bin/madscience:49:in `block in <top (required)>'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/gems/madscience-0.0.20/bin/madscience:42:in `in_madscience_dir'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/gems/madscience-0.0.20/bin/madscience:49:in `<top (required)>'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/bin/madscience:23:in `load'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/bin/madscience:23:in `<main>'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/michaelchrisco/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by lamont-granquist** [comment]
If this is an rdoc/sdoc/ri issue then it'll probably never get fixed.  If using --no-rdoc --no-ri or --no-document 'fixes' the problem then that is the likely workaround.  If you can replicate with YARD, while not involving any other gems like madscience then its more likely to be treated like a legitimate bug.  If you can find the bug yourself, then you could submit a pull request.
