### ISSUE TITLE
installation on macosx failed due to darwin# increase

### ISSUE THREAD

**Issue by UltimateGeek** [chef/libyajl2-gem#9]
Output from sudo gem install:

```
Fetching: libyajl2-1.2.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing chefspec:
	ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile
/Library/Ruby/Gems/2.0.0/gems/libyajl2-1.2.0/ext/libyajl2
extconf.rb:104:in `makemakefiles': unhandled exception
	from extconf.rb:138:in `<main>'
```

Attempt to build by hand:

```
$ ruby extconf.rb 
creating Makefile
/tmp/libyajl2-1.2.0/ext/libyajl2
extconf.rb:104:in `makemakefiles': unhandled exception
from extconf.rb:138:in `<main>'
$ make
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14/ruby/config.h', needed by `yajl.o'.  Stop.
```

Workaround:

```
$ cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/
$ sudo ln -s universal-darwin15 universal-darwin14
$ sudo gem install libyajl2
Building native extensions.  This could take a while...
Successfully installed libyajl2-1.2.0
```

**Comment by lamont-granquist** [comment]
what version of MacOSX?

**Comment by lamont-granquist** [comment]
````
15:04 coredump oc/chef # gem install libyajl2
Fetching: libyajl2-1.2.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed libyajl2-1.2.0
1 gem installed
git:chef:master rvm:
15:04 coredump oc/chef # uname -a
Darwin coredump.scriptkiddie.lan 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

doesn't replicate on my desktop

**Comment by lamont-granquist** [comment]
`xcode-select --install`  might fix it. 

i don't even have that installed, i suspect your installation of xcode is botched or old or has cruft left over from an upgrade.

**Comment by UltimateGeek** [comment]
Your suggestion worked. After running `xcode-select --install`:
```
$ sudo gem uninstall libyajl2

You have requested to uninstall the gem:
	libyajl2-1.2.0

ffi-yajl-2.2.3 depends on libyajl2 (~> 1.2)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled libyajl2-1.2.0
$ sudo gem install libyajl2
Fetching: libyajl2-1.2.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed libyajl2-1.2.0
Parsing documentation for libyajl2-1.2.0
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/libyajl2/vendored-libyajl2/lib/libyajl.bundle, skipping
Installing ri documentation for libyajl2-1.2.0
1 gem installed
$ uname -a
Darwin C02ML8T5FD57 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```

**Comment by UltimateGeek** [comment]
I should mention I also undid my workaround by removing the symlink before reinstalling the gem.
